In [1]:
import pandas as pd
import numpy as np

# excel 데이터 가공함수

In [2]:
# 단, 국토 교통부 실거래가 공개시스템에서 제공한 excel(*.xlsx)데이터만 가능.
# 직접 불필요한 데이터를 삭제할 팔요없이
# 코드를 이용해서 불필요한 데이터를 삭제하여
# 원하는 데이터를 수집할 수 있도록 만드는 함수

def modify_clumsy_raw_data(df):
    # 원하는 데이터의 컬럼(엑셀파일의 17행)
    target_cols=df.iloc[15].values
    
    # 데이터 컬럼 수정(딕셔너리 구조) 할때 필요.
    # 과거컬럼(딕셔너리 key값): 현재컬럼(딕셔너리 value값)
    change_cols=dict( [(org,new) for org, new in  zip(df.columns, target_cols)])
    
    # 컬럼바꾸기
    df.rename( columns=change_cols, inplace=True)
    
    # 원하는 데이터 (엑셀파일의 18행~마지막행)
    df= df[16:]
    
    # reset_index() : 인덱스번호 시작, index컬럼 안보이게함.
    df.reset_index(drop=True, inplace=True)
    
    return df

In [3]:
# 테스트01
test_df=pd.read_excel('./서울/아파트매매_실거래가.xlsx', encoding='euc-kr')
test_df.head(20)

,□ 본 서비스에서 제공하는 정보는 법적인 효력이 없으므로 참고용으로만 활용하시기 바랍니다.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,"□ 신고정보가 실시간 변경, 해제되어 제공시점에 따라 공개건수 및 내용이 상이할 수...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"□ 본 자료는 계약일 기준입니다. (※ 7월 계약, 8월 신고건 → 7월 거래건으로...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"□ 통계자료 활용시에는 수치가 왜곡될 수 있으니 참고자료로만 활용하시기 바라며, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,* 주택매매 거래는 부동산 거래신고 등에 관한 법률 제3조에 따라 계약일로부터 60...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,* 국토교통부 실거래가 공개시스템의 궁금하신 점이나 문의사항은 콜센터 1588-01...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,□ 검색조건,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,계약일자 : 20190901 ~ 20190930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,실거래 구분 : 아파트(매매),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,주소구분 : 지번주소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,시도 : 서울특별시,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,시군구 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,읍면동 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,면적 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,금액선택 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
16,서울특별시 강남구 개포동,658-1,0658,0001,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3
17,서울특별시 강남구 개포동,658-1,0658,0001,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3
18,서울특별시 강남구 개포동,12-2,0012,0002,개포자이(12-2),170.32,201909,2,"213,000",10,2004,개포로109길 69
19,서울특별시 강남구 개포동,141,0141,0000,개포주공 1단지,49.56,201909,2,"225,000",3,1982,선릉로 7

In [4]:
result_df=modify_clumsy_raw_data(test_df)

In [5]:
result_df.head(3)

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,서울특별시 강남구 개포동,658-1,0658,0001,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3
1,서울특별시 강남구 개포동,658-1,0658,0001,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3
2,서울특별시 강남구 개포동,12-2,0012,0002,개포자이(12-2),170.32,201909,2,"213,000",10,2004,개포로109길 69

In [6]:
# 테스트02
test_df2=pd.read_excel('./서울/연립다세대_실거래가.xlsx', encoding='euc-kr')
test_df2.head(20)

,□ 본 서비스에서 제공하는 정보는 법적인 효력이 없으므로 참고용으로만 활용하시기 바랍니다.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,"□ 신고정보가 실시간 변경, 해제되어 제공시점에 따라 공개건수 및 내용이 상이할 수...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"□ 본 자료는 계약일 기준입니다. (※ 7월 계약, 8월 신고건 → 7월 거래건으로...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"□ 통계자료 활용시에는 수치가 왜곡될 수 있으니 참고자료로만 활용하시기 바라며, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,* 주택매매 거래는 부동산 거래신고 등에 관한 법률 제3조에 따라 계약일로부터 60...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,* 국토교통부 실거래가 공개시스템의 궁금하신 점이나 문의사항은 콜센터 1588-01...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,□ 검색조건,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,계약일자 : 20190901 ~ 20190930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,실거래 구분 : 연립다세대(매매),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,주소구분 : 지번주소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,시도 : 서울특별시,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,시군구 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,읍면동 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,면적 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,금액선택 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,시군구,번지,본번,부번,건물명,전용면적(㎡),대지권면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
16,서울특별시 강남구 개포동,1249-1,1249,0001,골든빌리지,32.81,23.43,201909,3,"30,000",4,2014,개포로21길 11
17,서울특별시 강남구 개포동,1265-6,1265,0006,동산빌,48.32,23.58,201909,9,"30,000",5,2004,개포로31길 29-3
18,서울특별시 강남구 개포동,1205-8,1205,0008,두리빌,71.07,36.97,201909,2,"46,600",3,2002,개포로24길 23
19,서울특별시 강남구 개포동,1252-5,1252,0005,우리빌라,67.09,36.42,201909,12,"51,500",3,2004,개포로21길 27

In [7]:
result_df2=modify_clumsy_raw_data(test_df2)
result_df2.head(3)

,시군구,번지,본번,부번,건물명,전용면적(㎡),대지권면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,서울특별시 강남구 개포동,1249-1,1249,0001,골든빌리지,32.81,23.43,201909,3,"30,000",4,2014,개포로21길 11
1,서울특별시 강남구 개포동,1265-6,1265,0006,동산빌,48.32,23.58,201909,9,"30,000",5,2004,개포로31길 29-3
2,서울특별시 강남구 개포동,1205-8,1205,0008,두리빌,71.07,36.97,201909,2,"46,600",3,2002,개포로24길 23

<br><br><br>



# 여러개의 데이터를 원하는 데이터셋으로 가공

1) 국토교통부 실거래가 공개시스템에서 여러개 데이터를 얻는다.<br>
- 계약일자: 20190101~ 20191231 
- 파일구분: Excel<br>
- 실거래가구분: 아파트, 연립/다세대, 단독/다가구, 오피스텔(매매, 전월세) 
- 시도: 충청남도
- 시군구: 천안시 동남구
- 읍면동: 안서동/(전체)<br>

In [8]:
import pandas as pd
import numpy as np
from glob import glob
import seaborn as sns #시각화
import matplotlib.pyplot as plt # 시각화
from matplotlib import font_manager, rc # 시각화할때 한글폰트 나타내기
%matplotlib inline


# font_path: 글씨 폰트 path
font_path='C:/Windows/Fonts/malgun.ttf' #맑은고딕체
font_name= font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font_name)

In [9]:
def collect_modified_datas(raw_data_group , modify_data_group):
    for now_raw_data in raw_data_group:
        print('현재 수행파일명: {0}'.format(now_raw_data))
        
        # 데이터 가공 이전
        now_raw_df= pd.read_excel( now_raw_data, encoding='euc-kr')

        # 데이터 가공 이후
        now_df= modify_clumsy_raw_data(now_raw_df)

        # modify_data_group에 가공한 데이터를 추가
        modify_data_group.append(now_df)

<br><br>
## 1. 거래유형: 매매

In [10]:
# 매매 데이터 위치
trade_data_paths=r'./천안/매매/'

raw_trade_datas= glob(trade_data_paths+'*.xlsx')
raw_trade_datas

['./천안/매매\\단독다가구(매매)_실거래가_20191029010845.xlsx',
 './천안/매매\\아파트(매매)_실거래가_20191029010748.xlsx',
 './천안/매매\\연립다세대(매매)_실거래가_20191029010828.xlsx']

In [11]:
modify_trade_datas=[]

# modifiy_culumsy_raw_data()를 이용하여 원본데이터를 가공
collect_modified_datas(raw_trade_datas , modify_trade_datas)

현재 수행파일명: ./천안/매매\단독다가구(매매)_실거래가_20191029010845.xlsx
현재 수행파일명: ./천안/매매\아파트(매매)_실거래가_20191029010748.xlsx
현재 수행파일명: ./천안/매매\연립다세대(매매)_실거래가_20191029010828.xlsx

In [12]:
#매매-단독/다가구-실거래가
modify_trade_datas[0].head(3)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,충청남도 천안동남구 안서동,2**,다가구,8m미만,634.86,256,201907,15,"105,946",2003,각원사길
1,충청남도 천안동남구 안서동,3**,다가구,8m미만,493.29,270,201901,3,"90,000",2015,문암4길
2,충청남도 천안동남구 안서동,2**,다가구,8m미만,490.95,327,201903,10,"77,500",2015,안서1길

In [13]:
len(modify_trade_datas[0].columns)

11

In [14]:
#매매-아파트-실거래가
modify_trade_datas[1].head(3)

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,84.96,201903,11,"17,000",6,2004,안서1길 5-16
1,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,84.7482,201903,19,"17,500",6,2004,안서1길 5-16
2,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,59.968,201904,27,"14,500",4,2004,안서1길 5-16

In [15]:
len(modify_trade_datas[1].columns)

12

In [16]:
#매매-연립다세대-실거래가
modify_trade_datas[2].head(3)

,시군구,번지,본번,부번,건물명,전용면적(㎡),대지권면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,충청남도 천안동남구 안서동,321-37,0321,0037,동아주택(가나),28.2,21.8,201905,29,"2,500",4,1994,탑골길 17
1,충청남도 천안동남구 안서동,345-4,0345,0004,문암하우스,21.6,37.18,201907,20,"4,590",1,1992,문암3길 6-3
2,충청남도 천안동남구 안서동,345-4,0345,0004,문암하우스,21.6,37.18,201907,20,"5,296",2,1992,문암3길 6-3

In [17]:
len(modify_trade_datas[2].columns)

13

<br><br>
## 2. 거래유형: 전월세

In [18]:
# 전월세 데이터 위치
rent_data_paths=r'./천안/전월세/'

raw_rent_datas= glob(rent_data_paths+'*.xlsx')
raw_rent_datas

['./천안/전월세\\단독다가구(전월세)_실거래가_20191029011020.xlsx',
 './천안/전월세\\아파트(전월세)_실거래가_20191029010937.xlsx',
 './천안/전월세\\연립다세대(전월세)_실거래가_20191029010959.xlsx',
 './천안/전월세\\오피스텔(전월세)_실거래가_20191029.xlsx']

In [19]:
modify_rent_datas=[]

# modifiy_culumsy_raw_data()를 이용하여 원본데이터를 가공
collect_modified_datas(raw_rent_datas, modify_rent_datas)

현재 수행파일명: ./천안/전월세\단독다가구(전월세)_실거래가_20191029011020.xlsx
현재 수행파일명: ./천안/전월세\아파트(전월세)_실거래가_20191029010937.xlsx
현재 수행파일명: ./천안/전월세\연립다세대(전월세)_실거래가_20191029010959.xlsx
현재 수행파일명: ./천안/전월세\오피스텔(전월세)_실거래가_20191029.xlsx

In [20]:
#단독다가구(전월세)
modify_rent_datas[0].head(2)

,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세(만원),건축년도,도로명
0,충청남도 천안동남구 안서동,3**,8m미만,14,전세,201901,15,"4,000",0,2012,상명대길
1,충청남도 천안동남구 안서동,3**,-,14.8,전세,201907,6,"4,000",0,2012,NaN

In [21]:
len(modify_rent_datas[0].columns)

11

<br><br>

In [22]:
#아파트(전월세)
modify_rent_datas[1].head(2)

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명
0,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,전세,123.1724,201905,4,"15,000",0,7,2004,안서1길 5-16
1,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,전세,84.96,201905,19,"12,000",0,3,2004,안서1길 5-16

In [23]:
len(modify_rent_datas[1].columns)

14

<br>
<br>

In [24]:
#연립다세대(전월세)
modify_rent_datas[2].head(2)

,시군구,번지,본번,부번,건물명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명
0,충청남도 천안동남구 안서동,284-17,0284,0017,선호빌라(3),월세,48,201902,22,"3,800",10,4,1994,각원사길 131
1,충청남도 천안동남구 안서동,284-17,0284,0017,선호빌라(3),월세,48,201902,22,"3,800",10,4,1994,각원사길 131

In [25]:
len(modify_rent_datas[2].columns)

14

<br><br>

In [26]:
#오피스텔(전월세)
modify_rent_datas[3].head(2)

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명
0,충청남도 천안동남구 안서동,279-2,0279,0002,(279-2),월세,26.87,201901,12,"1,500",36,3,2018,각원사길 119
1,충청남도 천안동남구 안서동,279-2,0279,0002,(279-2),월세,33.84,201902,13,"2,000",40,4,2018,각원사길 119

<br><br>


# 데이터 컬럼 정리하기

위의 결과를 참고하면 7개의 데이터프레임 modify_trade_datas(3개), modify_rent_datas(4개) 의 컬럼개수가 모두 다르다.

컬럼개수가 모두 달라서 하나의 데이터프레임으로 합치기 어렵다.

번거롭지만, 7개의 데이터프레임을 조정하기로 했다.

<br>

## 1. 매매 데이터(modify_trade_datas)


### 1-1. 단독다가구 - 매매 (modify_trade_datas[0])

- DataFrame 컬럼명 변경 참고자료
<br>: http://hleecaster.com/python-pandas-modifying-dataframes/


- DataFrame 중복된 데이터row 삭제
<br>: https://m.blog.naver.com/PostView.nhn?blogId=kiddwannabe&logNo=221329647335&categoryNo=0&proxyReferer=https%3A%2F%2Fwww.google.com%2F

In [27]:
# 새로운 컬럼 생성 '건물구분'

modify_trade_datas[0].loc[:, '건물구분' ]= modify_trade_datas[0].loc[:, '주택유형']

In [28]:
# 새로운 컬럼 생성 '거래구분'

modify_trade_datas[0].loc[:, '거래구분']= '매매'

In [29]:
# 새로운 컬럼 생성 '전세보증금(만원)' =0원 (매매는 0원으로 한다.)
# 새로운 컬럼 생성 '월세(만원)' =0원
# 새로운 컬럼 생성 '층'=np.nan
modify_trade_datas[0].loc[:, '전세보증금(만원)']=0
modify_trade_datas[0].loc[:, '월세(만원)']=0
modify_trade_datas[0].loc[:, '층']=np.nan

In [30]:
# '거래금액(만원)' -> '매매가(만원)'
modify_trade_datas[0].rename(columns={'거래금액(만원)':'매매가(만원)'}, inplace=True)

In [31]:
# 새로운 컬럼 생성 '도로명 주소'= '시군구' +'도로명'

modify_trade_datas[0].loc[:, '도로명주소']= modify_trade_datas[0].loc[:,'시군구']+' '+modify_trade_datas[0].loc[:, '도로명']

In [32]:
modify_trade_datas[0].head(3)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,매매가(만원),건축년도,도로명,건물구분,거래구분,전세보증금(만원),월세(만원),층,도로명주소
0,충청남도 천안동남구 안서동,2**,다가구,8m미만,634.86,256,201907,15,"105,946",2003,각원사길,다가구,매매,0,0,NaN,충청남도 천안동남구 안서동 각원사길
1,충청남도 천안동남구 안서동,3**,다가구,8m미만,493.29,270,201901,3,"90,000",2015,문암4길,다가구,매매,0,0,NaN,충청남도 천안동남구 안서동 문암4길
2,충청남도 천안동남구 안서동,2**,다가구,8m미만,490.95,327,201903,10,"77,500",2015,안서1길,다가구,매매,0,0,NaN,충청남도 천안동남구 안서동 안서1길

In [33]:
modify_trade_datas[0]=modify_trade_datas[0].loc[:, ['거래구분','건물구분', '층', '도로명주소', '계약년월', 
                              '계약일', '건축년도', '매매가(만원)','전세보증금(만원)', '월세(만원)']]

In [34]:
modify_trade_datas[0]

,거래구분,건물구분,층,도로명주소,계약년월,계약일,건축년도,매매가(만원),전세보증금(만원),월세(만원)
0,매매,다가구,NaN,충청남도 천안동남구 안서동 각원사길,201907,15,2003,"105,946",0,0
1,매매,다가구,NaN,충청남도 천안동남구 안서동 문암4길,201901,3,2015,"90,000",0,0
2,매매,다가구,NaN,충청남도 천안동남구 안서동 안서1길,201903,10,2015,"77,500",0,0
3,매매,다가구,NaN,충청남도 천안동남구 안서동 성불사길,201905,28,2002,"4,000",0,0
4,매매,다가구,NaN,충청남도 천안동남구 안서동 문암4길,201909,4,2003,"141,000",0,0
5,매매,다가구,NaN,충청남도 천안동남구 안서동 상명대길,201907,3,2002,"68,834",0,0
6,매매,다가구,NaN,충청남도 천안동남구 안서동 상명대길,201906,17,2008,"117,500",0,0
7,매매,다가구,NaN,충청남도 천안동남구 안서동 문암로,201904,30,2015,"140,000",0,0
8,매매,단독,NaN,충청남도 천안동남구 안서동 상명대길,201901,16,2016,"195,000",0,0
9,매매,단독,NaN,충청남도 천안동남구 안서동 문암5길,201903,14,2019,"210,000",0,0
10,매매,단독,NaN,충청남도 천안동남구 안서동 문암5길,201903,14,2019,"210,000",0,0

In [35]:
# 중복된 데이터 제거하기 
# 위의 결과에서 9번과 10번 데이터는 index를 제외한 나머지가 모두 같다.

# 동일한 데이터 있는지 검사
display(modify_trade_datas[0].duplicated()) #마지막 데이터에서 True가뜸.

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [36]:
# 중복된 행은 하나만 남기고 제거하기(10번 로우 제거) 
modify_trade_datas[0].drop_duplicates(inplace=True)

# 수정완성 데이터
modify_trade_datas[0]

,거래구분,건물구분,층,도로명주소,계약년월,계약일,건축년도,매매가(만원),전세보증금(만원),월세(만원)
0,매매,다가구,NaN,충청남도 천안동남구 안서동 각원사길,201907,15,2003,"105,946",0,0
1,매매,다가구,NaN,충청남도 천안동남구 안서동 문암4길,201901,3,2015,"90,000",0,0
2,매매,다가구,NaN,충청남도 천안동남구 안서동 안서1길,201903,10,2015,"77,500",0,0
3,매매,다가구,NaN,충청남도 천안동남구 안서동 성불사길,201905,28,2002,"4,000",0,0
4,매매,다가구,NaN,충청남도 천안동남구 안서동 문암4길,201909,4,2003,"141,000",0,0
5,매매,다가구,NaN,충청남도 천안동남구 안서동 상명대길,201907,3,2002,"68,834",0,0
6,매매,다가구,NaN,충청남도 천안동남구 안서동 상명대길,201906,17,2008,"117,500",0,0
7,매매,다가구,NaN,충청남도 천안동남구 안서동 문암로,201904,30,2015,"140,000",0,0
8,매매,단독,NaN,충청남도 천안동남구 안서동 상명대길,201901,16,2016,"195,000",0,0
9,매매,단독,NaN,충청남도 천안동남구 안서동 문암5길,201903,14,2019,"210,000",0,0

<br>

### 1-2. 아파트 - 매매(modify_trade_datas[1])

In [37]:
# 수정 이전 데이터 모습
modify_trade_datas[1].head(3)

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,84.96,201903,11,"17,000",6,2004,안서1길 5-16
1,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,84.7482,201903,19,"17,500",6,2004,안서1길 5-16
2,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,59.968,201904,27,"14,500",4,2004,안서1길 5-16

In [38]:
# 새로운 컬럼 생성 '거래구분'

modify_trade_datas[1].loc[:, '거래구분']='매매'

In [39]:
# 새로운 컬럼 생성 '건물구분'

modify_trade_datas[1].loc[:, '건물구분']='아파트'

In [40]:
# 새로운 컬럼 생성 '도로명주소'= '시군구'+'도로명'+'단지명'

modify_trade_datas[1].loc[:, '도로명주소']=modify_trade_datas[1].loc[:,'시군구']+' '+modify_trade_datas[1].loc[:,'도로명']+' '+modify_trade_datas[1].loc[:,'단지명']

In [41]:
# 새로운 컬럼 생성 '월세(만원)' =0원
# 새로운 컬럼 생성 '전세보증금(만원)'=0원
modify_trade_datas[1].loc[:, '월세(만원)']=0
modify_trade_datas[1].loc[:, '전세보증금(만원)']=0

In [42]:
# 컬럼명 수정
modify_trade_datas[1].rename(columns={'거래금액(만원)': '매매가(만원)'}, inplace=True)

In [43]:
# 데이터 재정의 : 재정의 이후 데이터 shape: 147 *10
modify_trade_datas[1]= modify_trade_datas[1].loc[:, ['거래구분','건물구분', '층', '도로명주소', '계약년월', 
                              '계약일', '건축년도', '매매가(만원)','전세보증금(만원)', '월세(만원)']]

In [44]:
# 중복되는 데이터 제거-> 중복데이터 제거후 shape: 137*10
modify_trade_datas[1].drop_duplicates(inplace=True)

In [45]:
# 수정완성한 데이터 
modify_trade_datas[1].reset_index(drop=True)

,거래구분,건물구분,층,도로명주소,계약년월,계약일,건축년도,매매가(만원),전세보증금(만원),월세(만원)
0,매매,아파트,6,충청남도 천안동남구 안서동 안서1길 5-16 고운여의주,201903,11,2004,"17,000",0,0
1,매매,아파트,6,충청남도 천안동남구 안서동 안서1길 5-16 고운여의주,201903,19,2004,"17,500",0,0
2,매매,아파트,4,충청남도 천안동남구 안서동 안서1길 5-16 고운여의주,201904,27,2004,"14,500",0,0
3,매매,아파트,8,충청남도 천안동남구 안서동 안서1길 5-16 고운여의주,201909,18,2004,"14,800",0,0
4,매매,아파트,8,충청남도 천안동남구 안서동 성불사길 41 대림1차이편한세상,201901,7,2005,"24,500",0,0
...,...,...,...,...,...,...,...,...,...,...
132,매매,아파트,1,충청남도 천안동남구 안서동 문암1길 68 안서금호어울림,201907,1,2009,"18,000",0,0
133,매매,아파트,7,충청남도 천안동남구 안서동 문암1길 68 안서금호어울림,201907,9,2009,"18,200",0,0
134,매매,아파트,19,충청남도 천안동남구 안서동 문암1길 68 안서금호어울림,201907,23,2009,"23,501",0,0
135,매매,아파트,10,충청남도 천안동남구 안서동 문암1길 68 안서금호어울림,201908,20,2009,"23,501",0,0
136,매매,아파트,17,충청남도 천안동남구 안서동 문암1길 68 안서금호어울림,201909,21,2009,"17,900",0,0

<br>

### 1-3. 연립다세대 -매매(modify_trade_datas[2])

In [46]:
# 수정 이전 데이터 모습
modify_trade_datas[2].head(3)

,시군구,번지,본번,부번,건물명,전용면적(㎡),대지권면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,충청남도 천안동남구 안서동,321-37,0321,0037,동아주택(가나),28.2,21.8,201905,29,"2,500",4,1994,탑골길 17
1,충청남도 천안동남구 안서동,345-4,0345,0004,문암하우스,21.6,37.18,201907,20,"4,590",1,1992,문암3길 6-3
2,충청남도 천안동남구 안서동,345-4,0345,0004,문암하우스,21.6,37.18,201907,20,"5,296",2,1992,문암3길 6-3

In [47]:
# 새로운 컬럼 생성 '거래구분'

modify_trade_datas[2].loc[:, '거래구분']='매매'

In [48]:
# 새로운 컬럼 생성 '건물구분'

modify_trade_datas[2].loc[:, '건물구분']='연립다세대'

In [49]:
# 새로운 컬럼 생성 '도로명주소'= '시군구'+'도로명'+'건물명'

modify_trade_datas[2].loc[:, '도로명주소']=modify_trade_datas[2].loc[:,'시군구']+' '+modify_trade_datas[2].loc[:,'도로명']+' '+modify_trade_datas[2].loc[:,'건물명']

In [50]:
# 새로운 컬럼 생성 '월세(만원)' =0원
# 새로운 컬럼 생성 '전세보증금(만원)'=0원
modify_trade_datas[2].loc[:, '월세(만원)']=0
modify_trade_datas[2].loc[:, '전세보증금(만원)']=0

In [51]:
# 컬럼명 수정: '거래금액(만원)'->'매매가(만원)'
modify_trade_datas[2].rename(columns={'거래금액(만원)': '매매가(만원)'}, inplace=True)

In [52]:
# 데이터 재정의 : 재정의 이후 데이터 shape: 55*10
modify_trade_datas[2]= modify_trade_datas[2].loc[:, ['거래구분','건물구분', '층', '도로명주소', '계약년월', 
                              '계약일', '건축년도', '매매가(만원)','전세보증금(만원)', '월세(만원)']]

In [53]:
# 중복되는 데이터 제거-> 중복데이터 제거후 shape: 22*10
modify_trade_datas[2].drop_duplicates(inplace=True)

In [54]:
# 수정완성한 데이터 
modify_trade_datas[2].reset_index(drop=True)

,거래구분,건물구분,층,도로명주소,계약년월,계약일,건축년도,매매가(만원),전세보증금(만원),월세(만원)
0,매매,연립다세대,4,충청남도 천안동남구 안서동 탑골길 17 동아주택(가나),201905,29,1994,"2,500",0,0
1,매매,연립다세대,1,충청남도 천안동남구 안서동 문암3길 6-3 문암하우스,201907,20,1992,"4,590",0,0
2,매매,연립다세대,2,충청남도 천안동남구 안서동 문암3길 6-3 문암하우스,201907,20,1992,"5,296",0,0
3,매매,연립다세대,4,충청남도 천안동남구 안서동 문암3길 6-3 문암하우스,201907,20,1992,"4,943",0,0
4,매매,연립다세대,3,충청남도 천안동남구 안서동 문암3길 6-3 문암하우스,201907,20,1992,"5,296",0,0
5,매매,연립다세대,-1,충청남도 천안동남구 안서동 각원사길 30 크로바하이츠,201901,10,2001,"2,587",0,0
6,매매,연립다세대,-1,충청남도 천안동남구 안서동 각원사길 30 크로바하이츠,201901,10,2001,"2,787",0,0
7,매매,연립다세대,2,충청남도 천안동남구 안서동 각원사길 30 크로바하이츠,201901,10,2001,"4,379",0,0
8,매매,연립다세대,2,충청남도 천안동남구 안서동 각원사길 30 크로바하이츠,201901,10,2001,"3,981",0,0
9,매매,연립다세대,3,충청남도 천안동남구 안서동 각원사길 30 크로바하이츠,201901,10,2001,"4,379",0,0
10,매매,연립다세대,3,충청남도 천안동남구 안서동 각원사길 30 크로바하이츠,201901,10,2001,"3,981",0,0
11,매매,연립다세대,4,충청남도 천안동남구 안서동 각원사길 30 크로바하이츠,201901,10,2001,"12,148",0,0
12,매매,연립다세대,4,충청남도 천안동남구 안서동 각원사길 30 크로바하이츠,201901,10,2001,"4,181",0,0
13,매매,연립다세대,4,충청남도 천안동남구 안서동 각원사길 30 크로바하이츠,201901,10,2001,"3,782",0,0
14,매매,연립다세대,5,충청남도 천안동남구 안서동 문암2길 10-8 필유하우스(B),201903,7,2014,"8,125",0,0
15,매매,연립다세대,5,충청남도 천안동남구 안서동 문암2길 10-8 필유하우스(B),201903,7,2014,"6,500",0,0
16,매매,연립다세대,4,충청남도 천안동남구 안서동 문암2길 10-8 필유하우스(B),201903,7,2014,"8,125",0,0
17,매매,연립다세대,4,충청남도 천안동남구 안서동 문암2길 10-8 필유하우스(B),201903,7,2014,"6,500",0,0
18,매매,연립다세대,3,충청남도 천안동남구 안서동 문암2길 10-8 필유하우스(B),201903,7,2014,"8,125",0,0
19,매매,연립다세대,3,충청남도 천안동남구 안서동 문암2길 10-8 필유하우스(B),201903,7,2014,"6,500",0,0
20,매매,연립다세대,2,충청남도 천안동남구 안서동 문암2길 10-8 필유하우스(B),201903,7,2014,"6,500",0,0
21,매매,연립다세대,2,충청남도 천안동남구 안서동 문암2길 10-8 필유하우스(B),201903,7,2014,"8,125",0,0

<br>

## 2. 전월세 데이터(modify_rent_datas)

### 2-1. 단독다가구 - 전월세(modify_rent_datas[0])

In [55]:
# 수정 이전 데이터 모습
modify_rent_datas[0].head(3)

,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세(만원),건축년도,도로명
0,충청남도 천안동남구 안서동,3**,8m미만,14,전세,201901,15,"4,000",0,2012,상명대길
1,충청남도 천안동남구 안서동,3**,-,14.8,전세,201907,6,"4,000",0,2012,NaN
2,충청남도 천안동남구 안서동,3**,8m미만,14.8,전세,201901,22,"4,000",0,2012,상명대길

In [56]:
# 새로운 컬럼 생성 '거래구분'

modify_rent_datas[0].loc[:, '거래구분']=modify_rent_datas[0].loc[:, '전월세구분']

In [57]:
# 새로운 컬럼 생성 '건물구분'

modify_rent_datas[0].loc[:,'건물구분']='단독/다가구'

In [58]:
# 중복된 데이터를 없앤다

modify_rent_datas[0].drop_duplicates(inplace=True)

In [59]:
# 도로명이 NaN인 데이터는 제거한다.
# 즉, 도로명이 NaN이 아닌 데이터만 갖겠다는 뜻.
# df= df[~df['컬럼'].isnull()] =>  df['컬럼'].isnull() 이 True가 아닌 모든 데이터로우에 해당..
modify_rent_datas[0]= modify_rent_datas[0][~modify_rent_datas[0]['도로명'].isnull()]

modify_rent_datas[0].reset_index(inplace=True)

In [60]:
# 새로운 컬럼 생성 '도로명주소'='시군구'+'도로명'

modify_rent_datas[0].loc[:, '도로명주소']=modify_rent_datas[0].loc[:,'시군구']+' '+modify_rent_datas[0].loc[:,'도로명']

In [61]:
# 새로운 컬럼 생성 '매매가(만원)' =0원
modify_rent_datas[0].loc[:, '매매가(만원)']=0

In [62]:
# 새로운 컬럼 생성 '층'
modify_rent_datas[0].loc[:, '층']=np.nan

In [63]:
# 컬럼명 수정: '보증금(만원)'->'전세보증금(만원)'
modify_rent_datas[0].rename(columns={'보증금(만원)': '전세보증금(만원)'}, inplace=True)

In [64]:
# 데이터 재정의 : 재정의 이후 데이터 shape: 67*10
modify_rent_datas[0]= modify_rent_datas[0].loc[:, ['거래구분','건물구분', '층', '도로명주소', '계약년월', 
                              '계약일', '건축년도', '매매가(만원)','전세보증금(만원)', '월세(만원)']]

In [93]:
# 중복되는 데이터 제거-> 중복데이터 제거후 shape: 67*10
modify_rent_datas[0].drop_duplicates(inplace=True)

In [94]:
# 수정완성된 데이터
modify_rent_datas[0].reset_index(drop=True)

,거래구분,건물구분,층,도로명주소,계약년월,계약일,건축년도,매매가(만원),전세보증금(만원),월세(만원)
0,전세,단독/다가구,NaN,충청남도 천안동남구 안서동 상명대길,201901,15,2012,0,"4,000",0
1,전세,단독/다가구,NaN,충청남도 천안동남구 안서동 상명대길,201901,22,2012,0,"4,000",0
2,전세,단독/다가구,NaN,충청남도 천안동남구 안서동 상명대길,201902,26,2012,0,"4,000",0
3,월세,단독/다가구,NaN,충청남도 천안동남구 안서동 문암4길,201906,5,1998,0,"1,500",32
4,전세,단독/다가구,NaN,충청남도 천안동남구 안서동 문암5길,201903,9,2019,0,"6,500",0
...,...,...,...,...,...,...,...,...,...,...
62,전세,단독/다가구,NaN,충청남도 천안동남구 안서동 성불사길,201908,5,2016,0,"6,000",0
63,전세,단독/다가구,NaN,충청남도 천안동남구 안서동 각원사길,201906,24,NaN,0,"8,500",0
64,전세,단독/다가구,NaN,충청남도 천안동남구 안서동 문암로,201907,10,2017,0,"10,000",0
65,전세,단독/다가구,NaN,충청남도 천안동남구 안서동 안서1길,201902,16,2003,0,"6,500",0
66,전세,단독/다가구,NaN,충청남도 천안동남구 안서동 문암1길,201902,27,2003,0,"4,000",0

<br>

### 2-2. 아파트 - 전월세(modify_rent_datas[1])

In [66]:
# 수정 이전 데이터 모습
modify_rent_datas[1].head(3)

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명
0,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,전세,123.1724,201905,4,"15,000",0,7,2004,안서1길 5-16
1,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,전세,84.96,201905,19,"12,000",0,3,2004,안서1길 5-16
2,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,전세,84.7482,201906,22,"12,000",0,5,2004,안서1길 5-16

In [67]:
# 새로운 컬럼 생성 '거래구분'

modify_rent_datas[1].loc[:, '거래구분']=modify_rent_datas[1].loc[:, '전월세구분']

In [68]:
# 새로운 컬럼 생성 '건물구분' => shape: 179행

modify_rent_datas[1].loc[:,'건물구분']='아파트'

In [69]:
# 도로명이 NaN인 데이터는 제거한다.
# 즉, 도로명이 NaN이 아닌 데이터만 갖겠다는 뜻.
# df= df[~df['컬럼'].isnull()] =>  df['컬럼'].isnull() 이 True가 아닌 모든 데이터로우에 해당..
modify_rent_datas[1]= modify_rent_datas[1][~modify_rent_datas[1]['도로명'].isnull()]

modify_rent_datas[1].reset_index(drop=True)

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명,거래구분,건물구분
0,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,전세,123.1724,201905,4,"15,000",0,7,2004,안서1길 5-16,전세,아파트
1,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,전세,84.96,201905,19,"12,000",0,3,2004,안서1길 5-16,전세,아파트
2,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,전세,84.7482,201906,22,"12,000",0,5,2004,안서1길 5-16,전세,아파트
3,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,전세,84.96,201908,10,"12,000",0,12,2004,안서1길 5-16,전세,아파트
4,충청남도 천안동남구 안서동,223-3,0223,0003,고운여의주,전세,84.96,201908,19,"11,000",0,1,2004,안서1길 5-16,전세,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,충청남도 천안동남구 안서동,365-3,0365,0003,안서금호어울림,전세,84.969,201907,7,"18,000",0,9,2009,문암1길 68,전세,아파트
175,충청남도 천안동남구 안서동,365-3,0365,0003,안서금호어울림,전세,84.969,201907,30,"18,000",0,15,2009,문암1길 68,전세,아파트
176,충청남도 천안동남구 안서동,365-3,0365,0003,안서금호어울림,전세,84.969,201909,3,"18,000",0,19,2009,문암1길 68,전세,아파트
177,충청남도 천안동남구 안서동,365-3,0365,0003,안서금호어울림,전세,84.969,201909,16,"18,000",0,19,2009,문암1길 68,전세,아파트
178,충청남도 천안동남구 안서동,365-3,0365,0003,안서금호어울림,전세,84.969,201909,18,"20,500",0,20,2009,문암1길 68,전세,아파트

In [70]:
# 새로운 컬럼 생성 '도로명주소'='시군구'+'도로명'+'단지명'

modify_rent_datas[1].loc[:, '도로명주소']=modify_rent_datas[1].loc[:,'시군구']+' '+modify_rent_datas[1].loc[:,'도로명']+modify_rent_datas[1].loc[:,'단지명']+'APT'

In [71]:
# 새로운 컬럼 생성 '매매가(만원)' =0원
modify_rent_datas[1].loc[:, '매매가(만원)']=0

In [72]:
# 컬럼명 수정: '보증금(만원)'->'전세보증금(만원)'
modify_rent_datas[1].rename(columns={'보증금(만원)': '전세보증금(만원)'}, inplace=True)

In [73]:
# 데이터 재정의 : 재정의 이후 데이터 shape: 179*10
modify_rent_datas[1]= modify_rent_datas[1].loc[:, ['거래구분','건물구분', '층', '도로명주소', '계약년월', 
                              '계약일', '건축년도', '매매가(만원)','전세보증금(만원)', '월세(만원)']]

In [91]:
# 중복되는 데이터 제거-> 중복데이터 제거후 shape: 164*10
modify_rent_datas[1].drop_duplicates(inplace=True)

In [92]:
# 수정완성된 데이터
modify_rent_datas[1].reset_index(drop=True)

,거래구분,건물구분,층,도로명주소,계약년월,계약일,건축년도,매매가(만원),전세보증금(만원),월세(만원)
0,전세,아파트,7,충청남도 천안동남구 안서동 안서1길 5-16고운여의주APT,201905,4,2004,0,"15,000",0
1,전세,아파트,3,충청남도 천안동남구 안서동 안서1길 5-16고운여의주APT,201905,19,2004,0,"12,000",0
2,전세,아파트,5,충청남도 천안동남구 안서동 안서1길 5-16고운여의주APT,201906,22,2004,0,"12,000",0
3,전세,아파트,12,충청남도 천안동남구 안서동 안서1길 5-16고운여의주APT,201908,10,2004,0,"12,000",0
4,전세,아파트,1,충청남도 천안동남구 안서동 안서1길 5-16고운여의주APT,201908,19,2004,0,"11,000",0
...,...,...,...,...,...,...,...,...,...,...
159,전세,아파트,9,충청남도 천안동남구 안서동 문암1길 68안서금호어울림APT,201907,7,2009,0,"18,000",0
160,전세,아파트,15,충청남도 천안동남구 안서동 문암1길 68안서금호어울림APT,201907,30,2009,0,"18,000",0
161,전세,아파트,19,충청남도 천안동남구 안서동 문암1길 68안서금호어울림APT,201909,3,2009,0,"18,000",0
162,전세,아파트,19,충청남도 천안동남구 안서동 문암1길 68안서금호어울림APT,201909,16,2009,0,"18,000",0
163,전세,아파트,20,충청남도 천안동남구 안서동 문암1길 68안서금호어울림APT,201909,18,2009,0,"20,500",0

### 2-3. 연립다세대 - 전월세(modify_rent_datas[2])

In [75]:
# 수정 이전 데이터 모습
modify_rent_datas[2].head(3)

,시군구,번지,본번,부번,건물명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명
0,충청남도 천안동남구 안서동,284-17,0284,0017,선호빌라(3),월세,48,201902,22,"3,800",10,4,1994,각원사길 131
1,충청남도 천안동남구 안서동,284-17,0284,0017,선호빌라(3),월세,48,201902,22,"3,800",10,4,1994,각원사길 131
2,충청남도 천안동남구 안서동,318-113,0318,0113,천문주택,전세,16.17,201901,5,"5,000",0,3,2012,중암1길 14-1

In [77]:
# 새로운 컬럼 생성 '거래구분'

modify_rent_datas[2].loc[:, '거래구분']=modify_rent_datas[2].loc[:, '전월세구분']

In [79]:
# 새로운 컬럼 생성 '건물구분' 

modify_rent_datas[2].loc[:,'건물구분']='연립다세대'

In [81]:
# 새로운 컬럼 생성 '도로명주소'='시군구'+'도로명'+'건물명'

modify_rent_datas[2].loc[:, '도로명주소']=modify_rent_datas[2].loc[:,'시군구']+' '+modify_rent_datas[2].loc[:,'도로명']+modify_rent_datas[2].loc[:,'건물명']

In [83]:
# 새로운 컬럼 생성 '매매가(만원)' =0원
modify_rent_datas[2].loc[:, '매매가(만원)']=0

In [85]:
# 컬럼명 수정: '보증금(만원)'->'전세보증금(만원)'
modify_rent_datas[2].rename(columns={'보증금(만원)': '전세보증금(만원)'}, inplace=True)

In [87]:
# 데이터 재정의 : 재정의 이후 데이터 shape: 10*10
modify_rent_datas[2]= modify_rent_datas[2].loc[:, ['거래구분','건물구분', '층', '도로명주소', '계약년월', 
                              '계약일', '건축년도', '매매가(만원)','전세보증금(만원)', '월세(만원)']]

In [89]:
# 중복되는 데이터 제거-> 중복데이터 제거후 shape: 10*10
modify_rent_datas[2].drop_duplicates(inplace=True)

In [90]:
modify_rent_datas[2]

,거래구분,건물구분,층,도로명주소,계약년월,계약일,건축년도,매매가(만원),전세보증금(만원),월세(만원)
0,월세,연립다세대,4,충청남도 천안동남구 안서동 각원사길 131선호빌라(3),201902,22,1994,0,"3,800",10
2,전세,연립다세대,3,충청남도 천안동남구 안서동 중암1길 14-1천문주택,201901,5,2012,0,"5,000",0
3,전세,연립다세대,1,충청남도 천안동남구 안서동 중암1길 14-1천문주택,201902,8,2012,0,"5,000",0
4,전세,연립다세대,3,충청남도 천안동남구 안서동 중암1길 14-1천문주택,201906,30,2012,0,"5,000",0
5,전세,연립다세대,3,충청남도 천안동남구 안서동 중암1길 14-1천문주택,201907,12,2012,0,"6,000",0
6,전세,연립다세대,2,충청남도 천안동남구 안서동 중암1길 14-1천문주택,201908,28,2012,0,"5,000",0
7,전세,연립다세대,3,충청남도 천안동남구 안서동 각원사길 127평화빌라(1),201901,10,1995,0,"3,500",0
8,전세,연립다세대,2,충청남도 천안동남구 안서동 각원사길 127평화빌라(1),201901,28,1995,0,"3,500",0
9,전세,연립다세대,3,충청남도 천안동남구 안서동 안서1길 2-1행복한집,201905,6,2002,0,"4,000",0

### 2-4. 오피스텔 - 전월세(modify_rent_datas[3])

In [76]:
# 수정 이전 데이터 모습
modify_rent_datas[3].head(3)

,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명
0,충청남도 천안동남구 안서동,279-2,0279,0002,(279-2),월세,26.87,201901,12,"1,500",36,3,2018,각원사길 119
1,충청남도 천안동남구 안서동,279-2,0279,0002,(279-2),월세,33.84,201902,13,"2,000",40,4,2018,각원사길 119
2,충청남도 천안동남구 안서동,279-2,0279,0002,(279-2),월세,33.02,201902,15,"2,500",33,6,2018,각원사길 119

In [96]:
# 새로운 컬럼 생성 '거래구분'

modify_rent_datas[3].loc[:, '거래구분']=modify_rent_datas[3].loc[:, '전월세구분']

In [97]:
# 새로운 컬럼 생성 '건물구분' 

modify_rent_datas[3].loc[:,'건물구분']='오피스텔'

In [99]:
# 새로운 컬럼 생성 '도로명주소'='시군구'+'도로명'+'단지명'

modify_rent_datas[3].loc[:, '도로명주소']=modify_rent_datas[3].loc[:,'시군구']+' '+modify_rent_datas[3].loc[:,'도로명']+modify_rent_datas[3].loc[:,'단지명']

In [101]:
# 새로운 컬럼 생성 '매매가(만원)' =0원
modify_rent_datas[3].loc[:, '매매가(만원)']=0

In [102]:
# 컬럼명 수정: '보증금(만원)'->'전세보증금(만원)'
modify_rent_datas[3].rename(columns={'보증금(만원)': '전세보증금(만원)'}, inplace=True)

In [104]:
# 데이터 재정의 : 재정의 이후 데이터 shape: 11*10
modify_rent_datas[3]= modify_rent_datas[3].loc[:, ['거래구분','건물구분', '층', '도로명주소', '계약년월', 
                              '계약일', '건축년도', '매매가(만원)','전세보증금(만원)', '월세(만원)']]

In [106]:
# 중복되는 데이터 제거-> 중복데이터 제거후 shape: 11*10
modify_rent_datas[3].drop_duplicates(inplace=True)

In [107]:
modify_rent_datas[3]

,거래구분,건물구분,층,도로명주소,계약년월,계약일,건축년도,매매가(만원),전세보증금(만원),월세(만원)
0,월세,오피스텔,3,충청남도 천안동남구 안서동 각원사길 119(279-2),201901,12,2018,0,"1,500",36
1,월세,오피스텔,4,충청남도 천안동남구 안서동 각원사길 119(279-2),201902,13,2018,0,"2,000",40
2,월세,오피스텔,6,충청남도 천안동남구 안서동 각원사길 119(279-2),201902,15,2018,0,"2,500",33
3,월세,오피스텔,4,충청남도 천안동남구 안서동 각원사길 119(279-2),201902,21,2018,0,"1,000",40
4,월세,오피스텔,4,충청남도 천안동남구 안서동 각원사길 119(279-2),201902,23,2018,0,"2,000",40
5,월세,오피스텔,5,충청남도 천안동남구 안서동 각원사길 119(279-2),201902,23,2018,0,500,55
6,월세,오피스텔,6,충청남도 천안동남구 안서동 각원사길 119(279-2),201902,26,2018,0,500,45
7,월세,오피스텔,5,충청남도 천안동남구 안서동 각원사길 119(279-2),201902,26,2018,0,"1,500",35
8,월세,오피스텔,3,충청남도 천안동남구 안서동 각원사길 119(279-2),201902,27,2018,0,"1,500",35
9,월세,오피스텔,7,충청남도 천안동남구 안서동 각원사길 119(279-2),201903,1,2018,0,500,45
10,월세,오피스텔,8,충청남도 천안동남구 안서동 각원사길 119(279-2),201907,26,2018,0,"2,000",30

<br>

# 7개의 데이터 프레임들을 하나로 합친다.

In [110]:
#1. 통합데이터정의 : result_data
result_data= []

#2. 매매 데이터들을  통합데이터(result_data)에 append
for trade_df in modify_trade_datas:
    result_data.append(trade_df)
    
#3. 전월세 데이터들을 통합데이터(result_data)에 append
for rent_df in modify_rent_datas:
    result_data.append(rent_df)
    
# 새로운결과파일로 저장
house_cheonan_20190101_20191231=pd.concat(result_data, ignore_index=True)
house_cheonan_20190101_20191231.to_csv('./house_cheonan_20190101_20191231.csv',encoding='utf-8', index=False)

In [111]:
house_cheonan_20190101_20191231.head(5)

,거래구분,건물구분,층,도로명주소,계약년월,계약일,건축년도,매매가(만원),전세보증금(만원),월세(만원)
0,매매,다가구,NaN,충청남도 천안동남구 안서동 각원사길,201907,15,2003,"105,946",0,0
1,매매,다가구,NaN,충청남도 천안동남구 안서동 문암4길,201901,3,2015,"90,000",0,0
2,매매,다가구,NaN,충청남도 천안동남구 안서동 안서1길,201903,10,2015,"77,500",0,0
3,매매,다가구,NaN,충청남도 천안동남구 안서동 성불사길,201905,28,2002,"4,000",0,0
4,매매,다가구,NaN,충청남도 천안동남구 안서동 문암4길,201909,4,2003,"141,000",0,0

# EDA