In [1]:
import pandas as pd
import numpy as np

In [2]:
sample_seoul_data= pd.read_excel('./서울/아파트매매_실거래가.xlsx', encoding='euc-kr')

# 엉뚱한 컬럼을 제대로 수정해보자.

xlsx파일을 받아보면 제대로된 데이터는 15행부터 존재한다.

여러개의 데이터를 다운받았을 때 하나의 파일의 1행~14행을 일일히 삭제하는건 비효율적이다.

자동으로 내가 원하는 데이터가 아닌 불필요한 미사여구들을 삭제하여 

내가 원하는 데이터만을 얻을 수 있는 방법이 없을까?

In [3]:
sample_seoul_data.head(18)

,□ 본 서비스에서 제공하는 정보는 법적인 효력이 없으므로 참고용으로만 활용하시기 바랍니다.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,"□ 신고정보가 실시간 변경, 해제되어 제공시점에 따라 공개건수 및 내용이 상이할 수...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"□ 본 자료는 계약일 기준입니다. (※ 7월 계약, 8월 신고건 → 7월 거래건으로...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"□ 통계자료 활용시에는 수치가 왜곡될 수 있으니 참고자료로만 활용하시기 바라며, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,* 주택매매 거래는 부동산 거래신고 등에 관한 법률 제3조에 따라 계약일로부터 60...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,* 국토교통부 실거래가 공개시스템의 궁금하신 점이나 문의사항은 콜센터 1588-01...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,□ 검색조건,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,계약일자 : 20190901 ~ 20190930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,실거래 구분 : 아파트(매매),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,주소구분 : 지번주소,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,시도 : 서울특별시,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,시군구 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,읍면동 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,면적 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,금액선택 : 전체,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
16,서울특별시 강남구 개포동,658-1,0658,0001,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3
17,서울특별시 강남구 개포동,658-1,0658,0001,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3

# 원본데이터의 엉뚱한 컬럼

In [4]:
sample_seoul_data.columns

Index(['□ 본 서비스에서 제공하는 정보는 법적인 효력이 없으므로 참고용으로만 활용하시기 바랍니다.', 'Unnamed: 1',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')

# 실제 데이터의 컬럼

원본데이터의 15행(엑셀파일17행) 데이터 레코드가 실제 컬럼이다.

In [5]:
sample_seoul_data_target_columns = sample_seoul_data.iloc[15].values
sample_seoul_data_target_columns

array(['시군구', '번지', '본번', '부번', '단지명', '전용면적(㎡)', '계약년월', '계약일',
       '거래금액(만원)', '층', '건축년도', '도로명'], dtype=object)

# 컬럼명 바꾸기 

(참고 url) https://blog.naver.com/PostView.nhn?blogId=okkam76&logNo=221374059438&redirect=Dlog&widgetTypeCall=true&directAccess=false

In [6]:
changed_cols=dict([(org,new) for org, new in zip(sample_seoul_data.columns, sample_seoul_data_target_columns)])
changed_cols

{'□ 본 서비스에서 제공하는 정보는 법적인 효력이 없으므로 참고용으로만 활용하시기 바랍니다.': '시군구',
 'Unnamed: 1': '번지',
 'Unnamed: 2': '본번',
 'Unnamed: 3': '부번',
 'Unnamed: 4': '단지명',
 'Unnamed: 5': '전용면적(㎡)',
 'Unnamed: 6': '계약년월',
 'Unnamed: 7': '계약일',
 'Unnamed: 8': '거래금액(만원)',
 'Unnamed: 9': '층',
 'Unnamed: 10': '건축년도',
 'Unnamed: 11': '도로명'}

In [7]:
# 컬럼 바꾸기 
sample_seoul_data.rename( columns=changed_cols, inplace=True)

In [8]:
sample_seoul_data= sample_seoul_data[16:]
sample_seoul_data.head(5)

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
16,서울특별시 강남구 개포동,658-1,0658,0001,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3
17,서울특별시 강남구 개포동,658-1,0658,0001,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3
18,서울특별시 강남구 개포동,12-2,0012,0002,개포자이(12-2),170.32,201909,2,"213,000",10,2004,개포로109길 69
19,서울특별시 강남구 개포동,141,0141,0000,개포주공 1단지,49.56,201909,2,"225,000",3,1982,선릉로 7
20,서울특별시 강남구 개포동,141,0141,0000,개포주공 1단지,50.64,201909,3,"250,000",3,1982,개포로 310

In [9]:
# reset_index
sample_seoul_data.reset_index(drop=True, inplace=True)

In [10]:
sample_seoul_data.head(5)

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명
0,서울특별시 강남구 개포동,658-1,0658,0001,개포6차우성아파트1동~8동,79.97,201909,2,"157,000",2,1987,언주로 3
1,서울특별시 강남구 개포동,658-1,0658,0001,개포6차우성아파트1동~8동,79.97,201909,10,"151,500",5,1987,언주로 3
2,서울특별시 강남구 개포동,12-2,0012,0002,개포자이(12-2),170.32,201909,2,"213,000",10,2004,개포로109길 69
3,서울특별시 강남구 개포동,141,0141,0000,개포주공 1단지,49.56,201909,2,"225,000",3,1982,선릉로 7
4,서울특별시 강남구 개포동,141,0141,0000,개포주공 1단지,50.64,201909,3,"250,000",3,1982,개포로 310